portal:
  hitbox:
    width: 2.0
    depth: 2.0
    height: 2.0
  teleport:
    cooldownSeconds: 3
    messageCooldownSeconds: 1
  gui:
    title: "§d§lSelect Portal"
    show-coordinates: true
    show-world: true
  craftablePortals:
    enabled: true
    defaultTexture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYjBiZmMyNTc3ZjZlMjZjNmM2ZjczNjVjMmM0MDc2YmNjZWU2NTMxMjQ5ODkzODJjZTkzYmNhNGZjOWUzOWIifX19"
    item:
      name: "§d§lPortal Crystal"
      lore:
        - "§7Place to create a personal portal"
        - "§7Rename in anvil to customize"
